# Generated by Django 2.2 on 2019-04-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('symbol', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.CheckConstraint(check=models.Q(value__gt=0), name='value_positive'),
        ),
    ]
